In [1]:
import pandas as pd
from bs4 import BeautifulSoup
import requests as r

url = 'https://www.al.sp.gov.br/repositorio/folha-de-pagamento/folha-2018-10-detalhada.html'
data = r.get(url).content
soup = BeautifulSoup(data, 'html.parser')
lista = []
for tr in soup.find_all('tr')[1:]:
    col = 0
    for i in tr.find_all('td'):
        td_limpo = i.get_text().strip()
        td_nmr_limpo = i.get_text().strip().replace('.', '').replace(',', '.')
        if col == 0:
            nome = td_limpo
        if col == 1:
            bruto = td_nmr_limpo
        if col == 2:
            liquido = td_nmr_limpo
        if col == 3:
            tributos = td_nmr_limpo
        if col == 4:
            abono_perm = td_nmr_limpo
        if col == 5:
            ferias_bruto = td_nmr_limpo
        if col == 6:
            ferias_desc = td_nmr_limpo
        if col == 7:
            ferias_liq = td_nmr_limpo
        if col == 8:
            bruto_13 = td_nmr_limpo
        if col == 9:
            desc_13 = td_nmr_limpo
        if col == 10:
            liq_13 = td_nmr_limpo
        if col == 11:
            retroativo_bruto = td_nmr_limpo
        if col == 12:
            retroativo_desc = td_nmr_limpo
        if col == 13:
            retroativo_liq = td_nmr_limpo
        if col == 14:
            outros_bruto = td_nmr_limpo
        if col == 15:
            outros_desc = td_nmr_limpo
        if col == 16:
            indenizacao = td_nmr_limpo
            lista.append({'nome': nome, 
                          'vlr_bruto': float(bruto), 
                          'vlr_liquido': float(liquido), 
                          'tributos': float(tributos), 
                          'abono_permanencia': float(abono_perm), 
                          'ferias_bruto': float(ferias_bruto), 
                          'ferias_liquido': float(ferias_liq),
                          'ferias_desconto': float(ferias_desc),
                          '13_bruto': float(bruto_13), 
                          '13_liquido': float(liq_13), 
                          '13_desconto': float(desc_13), 
                          'retroativo_bruto': float(retroativo_bruto), 
                          'retroativo_liquido': float(retroativo_liq), 
                          'retroativo_desconto': float(retroativo_desc), 
                          'outros_bruto': float(outros_bruto), 
                          'outros_desconto': float(outros_desc), 
                          'indenizacao': float(indenizacao)})
        col += 1
df = pd.DataFrame(lista, columns=['nome', 'vlr_bruto', 'vlr_liquido', 'tributos', 
                                  'abono_permanencia', 'ferias_bruto', 'ferias_liquido', 
                                  'ferias_desconto', '13_bruto', '13_liquido', '13_desconto', 
                                  'retroativo_bruto', 'retroativo_liquido', 
                                  'retroativo_desconto', 'outros_bruto', 
                                  'outros_desconto', 'indenizacao'])

In [2]:
df.head(10)

,nome,vlr_bruto,vlr_liquido,tributos,abono_permanencia,ferias_bruto,ferias_liquido,ferias_desconto,13_bruto,13_liquido,13_desconto,retroativo_bruto,retroativo_liquido,retroativo_desconto,outros_bruto,outros_desconto,indenizacao
0,ABALDINO FERREIRA DA SILVA,3257.68,2776.83,480.85,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,601.49,0.0,0.0
1,ABEL CASTILHO,1369.69,1292.01,77.68,0.0,0.0,0.0,0.0,228.28,228.28,0.00,0.00,0.00,0.0,0.00,0.0,0.0
2,ABEL PEREIRA,17670.21,13244.92,4425.29,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,306.88,0.0,0.0
3,ABENOR GARCIA FERREIRA,22919.10,17871.01,5048.09,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,306.88,0.0,0.0
4,ABILIO DO LIVRAMENTO P ALVES,15660.75,10919.05,4741.70,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,601.49,0.0,0.0
5,ABNEIA BUFFOLIN BROCANELLI,6704.12,5257.17,1446.95,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,908.37,0.0,0.0
6,ABNER REISES BARBOSA,1590.02,1437.87,152.15,0.0,0.0,0.0,0.0,2120.02,1927.33,192.69,-927.51,-927.51,0.0,300.74,0.0,0.0
7,ABRAAO MOREIRA DA SILVA,3257.68,2792.76,464.92,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,601.49,0.0,0.0
8,ABRAHAO RICARDO HACKME,10280.17,7804.42,2475.75,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,601.49,0.0,0.0
9,ACACIA DE ASSIS NEGREIROS,8717.24,7375.92,1341.32,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,127.03,0.0,0.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4970 entries, 0 to 4969
Data columns (total 17 columns):
nome                   4970 non-null object
vlr_bruto              4970 non-null float64
vlr_liquido            4970 non-null float64
tributos               4970 non-null float64
abono_permanencia      4970 non-null float64
ferias_bruto           4970 non-null float64
ferias_liquido         4970 non-null float64
ferias_desconto        4970 non-null float64
13_bruto               4970 non-null float64
13_liquido             4970 non-null float64
13_desconto            4970 non-null float64
retroativo_bruto       4970 non-null float64
retroativo_liquido     4970 non-null float64
retroativo_desconto    4970 non-null float64
outros_bruto           4970 non-null float64
outros_desconto        4970 non-null float64
indenizacao            4970 non-null float64
dtypes: float64(16), object(1)
memory usage: 640.7+ KB

In [4]:
df['nome'].nunique()

4952

In [5]:
df[df['nome'].duplicated(keep=False)]

,nome,vlr_bruto,vlr_liquido,tributos,abono_permanencia,ferias_bruto,ferias_liquido,ferias_desconto,13_bruto,13_liquido,13_desconto,retroativo_bruto,retroativo_liquido,retroativo_desconto,outros_bruto,outros_desconto,indenizacao
266,ANA MARIA DA SILVA,15512.33,11533.25,3979.08,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
267,ANA MARIA DA SILVA,11477.80,8643.21,2834.59,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
447,ANTONIO DOS SANTOS,18963.59,14066.82,4896.77,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
448,ANTONIO DOS SANTOS,13471.61,12990.27,481.34,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,241.54,0.0,0.0
906,CLAUDIO FERREIRA,14922.78,11062.24,3860.54,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
907,CLAUDIO FERREIRA,10399.47,10242.54,156.93,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,156.93,0.0,0.0
2174,JOAO CARLOS FRANCISCO DA SILVA,14643.96,10968.42,3675.54,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
2175,JOAO CARLOS FRANCISCO DA SILVA,19316.84,14345.50,4971.34,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,889.38,0.0,0.0
2326,JOSE CARLOS DUARTE DE TOLEDO,12043.71,8889.92,3153.79,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
2327,JOSE CARLOS DUARTE DE TOLEDO,13278.54,9600.05,3678.49,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,254.40,0.0,0.0
2337,JOSE CARLOS PEREIRA,16246.06,12047.56,4198.50,0.0,0.00,0.00,0.00,0.00,0.00,0.0,24.20,24.20,0.0,874.59,0.0,0.0
2338,JOSE CARLOS PEREIRA,15637.10,14902.20,734.90,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
2375,JOSE GONCALVES,16449.14,12250.90,4198.24,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,284.31,0.0,0.0
2376,JOSE GONCALVES,10207.82,7699.79,2508.03,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
2445,JOSE ROBERTO DA SILVA,8874.36,6780.67,2093.69,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
2446,JOSE ROBERTO DA SILVA,15512.33,11533.25,3979.08,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,632.75,0.0,0.0
2463,JOSE RUIZ NETTO,18846.10,13516.42,5329.68,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
2464,JOSE RUIZ NETTO,6476.15,4565.24,1910.91,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
2846,LUIZ FERNANDO DE CARVALHO,10084.45,7308.06,2776.39,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,890.83,0.0,0.0
2847,LUIZ FERNANDO DE CARVALHO,9859.06,7618.38,2240.68,0.0,0.00,0.00,0.00,0.00,0.00,0.0,9.96,9.96,0.0,601.49,124.0,0.0
3146,MARIA APARECIDA DE SOUZA,3257.68,2806.98,450.70,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
3147,MARIA APARECIDA DE SOUZA,10222.35,8373.10,1849.25,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,163.07,0.0,0.0
3366,MARILUCIA PARDINI OLBRICH ZANELATO BUCHI,21402.74,14753.48,6649.26,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
3367,MARILUCIA PARDINI OLBRICH ZANELATO BUCHI,3257.68,2228.98,1028.70,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
3822,PAULO EDUARDO ALVES FERREIRA,3257.68,2776.83,480.85,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
3823,PAULO EDUARDO ALVES FERREIRA,8178.56,6250.71,1927.85,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
3995,REINALDO DA SILVA,12942.92,9688.74,3254.18,0.0,4314.30,4022.38,291.92,5392.88,5392.88,0.0,276.06,276.06,0.0,908.37,0.0,0.0
3996,REINALDO DA SILVA,13778.72,10353.66,3425.06,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
4058,RICARDO DE OLIVEIRA,8090.38,6205.73,1884.65,0.0,1348.39,1348.39,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
4059,RICARDO DE OLIVEIRA,22680.24,16655.36,6024.88,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
4418,SHIGUERO ORITA,9030.40,6797.84,2232.56,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
4419,SHIGUERO ORITA,10815.97,8130.34,2685.63,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
4522,SONIA MARIA CARNEIRO D ALBUQUERQUE,10823.56,7856.94,2966.62,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
4523,SONIA MARIA CARNEIRO D ALBUQUERQUE,14498.69,10710.08,3788.61,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0
4563,SUELI SOARES FARIA DE OLIVEIRA,12731.97,9531.17,3200.80,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,306.88,0.0,0.0
4564,SUELI SOARES FARIA DE OLIVEIRA,8902.51,6552.48,2350.03,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,601.49,0.0,0.0